### ISSUE TITLE
Looking for more killings

### ISSUE THREAD

**Issue by melmsie** [melmsie/Dank-Memer#18]
in arrays.json, we need more kill scenarios. 

If you take this on, `$mention` would be the person to be killed and `$author` would be the person doing the killing.

This would be a good PR for you if you wanna get a shirt for hacktober fest!

**Comment by melmsie** [comment]
I won't accept PR's with a small amount of them. Please make it more than 10 at least to be worth a PR.

**Comment by melmsie** [comment]
Could still use some more

**Comment by cfilby** [comment]
I'll go ahead and make some.

**Comment by melmsie** [comment]
awesome

**Comment by atiwiex** [comment]
PR #25

**Comment by melmsie** [comment]
Could always have more! Come on down hacktoberfesters looking for an easy PR!

**Comment by NoahJelen** [comment]
Here is a good death message: <discord user> died from listening to too much Slayer
