### ISSUE TITLE
Code needs linted

### ISSUE THREAD

**Issue by melmsie** [melmsie/Dank-Memer#26]
We need all code in the repo to be linted with [StandardJS](https://standardjs.com/).

Great task for anyone wanting a hacktoberfest tshirt!

**Comment by ivanseed** [comment]
I will pick this one up!

**Comment by ivanseed** [comment]
@melmsie Standard enforces indentation of spaces but at the moment tabs is used. Are you wanting to go with spaces going forward or you wanting to change the configuration?

**Comment by melmsie** [comment]
I would like to completely change to standardjs' 2 spaces @ivanseed
