### ISSUE TITLE
Update porn command

### ISSUE THREAD

**Issue by xXBuilderBXx** [melmsie/Dank-Memer#33]
Update the porn command with text saying you have to login to vote for the noobs to read ;)

**Comment by iamhansen** [comment]
just make it upvote only, 

boom 20k votes

**Comment by melmsie** [comment]
Feel free to submit a PR :-)

**Comment by iamhansen** [comment]
okay

**Comment by wasitacatisaw** [comment]
@melmsie 
why did you remove the text at a78271f22698440932914ff57c31e262bb0e99fb ??

**Comment by xXBuilderBXx** [comment]
Lol what is going on here

**Comment by tilda** [comment]
hopefully #37 fixes this
