### ISSUE TITLE
Bot implicitly relies on nonexistent tables in database

### ISSUE THREAD

**Issue by PUNISHED-BAYGE** [melmsie/Dank-Memer#40]
Needs to initialise the tables that it needs during setup or something.

**Comment by Aetheryx** [comment]
So far we've been creating the tables through the Rethink administrative panel, which has been fine for us. I know there's a way to programmatically create the tables, feel free to add that functionality in a PR

**Comment by melmsie** [comment]
+1 to what @Aetheryx said. Would be nifty to have, we're low on time right now however.

**Comment by PUNISHED-BAYGE** [comment]
I won't take this on - for now an amendment to the README could be suitable.

**Comment by melmsie** [comment]
@PUNISHED-BAYGE would you mind inviting me to the server with your selfhosted bot? I'd like to check out what you've changed for curiosity's sake.

**Comment by PUNISHED-BAYGE** [comment]
@melmsie Haha, tbh there haven't been any remarkable changes, just removed Datadog integration & added some different music commands. At some stage I'd like to explore a way for people to upload their own clips (since I don't need to be as concerned with bandwidth). Right now I can't unfortunately.
