### ISSUE TITLE
Memegen is broken

### ISSUE THREAD

**Issue by JLHackSeven** [melmsie/Dank-Memer#46]
![screenshot_2017-12-26-21-58-36](https://user-images.githubusercontent.com/15951495/34389596-605fccbe-eaef-11e7-8728-88cda773e87d.png)
![screenshot_2017-12-26-21-58-53](https://user-images.githubusercontent.com/15951495/34389600-68c7a6d8-eaef-11e7-8a47-699f591357f3.png)

**Comment by JLHackSeven** [comment]
![screenshot_2017-12-26-21-58-44](https://user-images.githubusercontent.com/15951495/34389609-8689fa5e-eaef-11e7-8792-4fa81b05facd.png)

**Comment by melmsie** [comment]
I'm aware of memegen being broken, but what's the issue with pepe?

**Comment by JLHackSeven** [comment]
None, I was just posting that as a joke

**Comment by JLHackSeven** [comment]
I've used memegen previously and it worked
When I encounter any neo-nazis/racists on discord who get anti-semetic I usually respond with
pls memegen One Does Not Simply = One Does Not Simply | Kill all the jews

**Comment by JLHackSeven** [comment]
Memegen is wonderful, and I really would like it working again, if it's possible

Every time I encounter a Neo-Nazi or racist dickhead who starts going on an anti-semetic rant, I always respond with
pls memegen One Does Not Simply = One does not simply | kill all the jews

When they see it, they stop and think for a second (as if this never occured to them) and generally lose their train of thought

**Comment by JLHackSeven** [comment]
Memegen is working now
Here's one with "Joker Rainbow Hands"
[https://cdn.discordapp.com/attachments/344956602669072384/400408623072935938/mymeme.png](url)
